### ISSUE TITLE
WARNING:root:NaN or Inf found in input tensor.

### ISSUE THREAD

**Issue by zzuyu** [menghuanlater/Tianchi2020ChineseMedicineQuestionGeneration#1]
能分享下环境吗？ 训练过程中loss消失了

**Comment by menghuanlater** [comment]
我当时用的conda环境有部分包升级过了，当时用的应该是3.2版本的transformers，1.6版本的pytorch
下面的是我现在的conda环境，你可以把那两个包版本降下去试试
# packages in environment at /home/ldmc/anaconda3/envs/anlin_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_tflow_select             2.3.0                       mkl    defaults
absl-py                   0.9.0                    py38_0    defaults
antlr4-python3-runtime    4.8                      pypi_0    pypi
astunparse                1.6.3                      py_0    defaults
beautifulsoup4            4.9.1                    pypi_0    pypi
blas                      1.0                         mkl    defaults
blinker                   1.4                      py38_0    defaults
brotlipy                  0.7.0           py38h7b6447c_1000    defaults
c-ares                    1.15.0            h7b6447c_1001    defaults
ca-certificates           2020.7.22                     0    defaults
cachetools                4.1.1                      py_0    defaults
certifi                   2020.6.20                py38_0    defaults
cffi                      1.14.2           py38he30daa8_0    defaults
chardet                   3.0.4                 py38_1003    defaults
click                     7.1.2                      py_0    defaults
cryptography              3.1              py38h1ba5d50_0    defaults
cudatoolkit               10.1.243             h6bb024c_0    defaults
cython                    0.29.21                  pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
datasets                  1.6.2                    pypi_0    pypi
dill                      0.3.3                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
editdistance              0.5.3                    pypi_0    pypi
faiss-cpu                 1.6.3                    pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
flask                     1.1.2                    pypi_0    pypi
fsspec                    2021.4.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                      py_0    defaults
google-auth               1.21.0                     py_0    defaults
google-auth-oauthlib      0.4.1                      py_2    defaults
google-pasta              0.2.0                      py_0    defaults
grpcio                    1.31.0           py38hf8bcb03_0    defaults
h5py                      2.10.0           py38hd6299e0_1    defaults
hdf5                      1.10.6               hb1b8bf9_0    defaults
huggingface-hub           0.0.8                    pypi_0    pypi
hydra-core                1.0.3                    pypi_0    pypi
idna                      2.10                       py_0    defaults
importlib-metadata        1.7.0                    py38_0    defaults
importlib-resources       3.3.0                    pypi_0    pypi
intel-openmp              2020.1                      217    defaults
itsdangerous              1.1.0                    pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
joblib                    0.16.0                     py_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libprotobuf               3.12.4               hd408876_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
markdown                  3.2.2                    py38_0    defaults
markupsafe                1.1.1                    pypi_0    pypi
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py38he904b0f_0    defaults
mkl_fft                   1.1.0            py38h23d657b_0    defaults
mkl_random                1.1.1            py38h0573a6f_0    defaults
multiprocess              0.70.11.1                pypi_0    pypi
ncurses                   6.2                  he6710b0_1    defaults
ninja                     1.9.0            py38hfd86e86_0    defaults
nltk                      3.5                      pypi_0    pypi
numpy                     1.18.5           py38ha1c710e_0    defaults
numpy-base                1.18.5           py38hde5b4d6_0    defaults
oauthlib                  3.1.0                      py_0    defaults
omegaconf                 2.0.3                    pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0    defaults
opt_einsum                3.1.0                      py_0    defaults
packaging                 20.4                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
pip                       20.1.1                   py38_1    defaults
portalocker               2.0.0                    pypi_0    pypi
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.7.3                    pypi_0    pypi
pyarrow                   2.0.0                    pypi_0    pypi
pyasn1                    0.4.8                      py_0    defaults
pyasn1-modules            0.2.7                      py_0    defaults
pycparser                 2.20                       py_2    defaults
pyjwt                     1.7.1                    py38_0    defaults
pymysql                   0.10.0                   pypi_0    pypi
pyopenssl                 19.1.0                     py_1    defaults
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1                    py38_0    defaults
python                    3.8.3                hcff3b4d_2    https://repo.anaconda.com/pkgs/main
python-dateutil           2.8.1                    pypi_0    pypi
python-levenshtein        0.12.0                   pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0    defaults
redis                     3.5.3                    pypi_0    pypi
regex                     2020.7.14                pypi_0    pypi
requests                  2.24.0                     py_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
rsa                       4.6                        py_0    defaults
sacrebleu                 1.4.14                   pypi_0    pypi
sacremoses                0.0.43                   pypi_0    pypi
scikit-learn              0.23.1           py38h423224d_0    defaults
scipy                     1.5.0            py38h0b6359f_0    defaults
selenium                  3.141.0                  pypi_0    pypi
sentencepiece             0.1.91                   pypi_0    pypi
setuptools                49.2.0                   py38_0    defaults
six                       1.15.0                     py_0    defaults
soupsieve                 2.0.1                    pypi_0    pypi
sqlite                    3.32.3               h62c20be_0    defaults
stanfordcorenlp           3.9.1.1                  pypi_0    pypi
tensorboard               2.2.1              pyh532a8cf_0    defaults
tensorboard-plugin-wit    1.6.0                      py_0    defaults
tensorboardx              2.1                      pypi_0    pypi
tensorflow                2.2.0           mkl_py38h6d3daf0_0    defaults
tensorflow-base           2.2.0           mkl_py38h5059a2d_0    defaults
tensorflow-estimator      2.2.0              pyh208ff02_0    defaults
termcolor                 1.1.0                    py38_1    defaults
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tokenizers                0.10.2                   pypi_0    pypi
torch                     1.6.0+cu101              pypi_0    pypi
tqdm                      4.29.1                   pypi_0    pypi
transformers              4.5.0                    pypi_0    pypi
twilio                    6.45.0                   pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.25.10                    py_0    defaults
werkzeug                  1.0.1                      py_0    defaults
wget                      3.2                      pypi_0    pypi
wheel                     0.34.2                   py38_0    defaults
wrapt                     1.12.1           py38h7b6447c_1    defaults
xxhash                    2.0.2                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults

**Comment by zzuyu** [comment]
好的，感谢，模型已经跑通了，想用做baseline来做一些其他短句生成的任务，为什么输入的句子长度比较短的时候，会出现WARNING:root:NaN or Inf found in input tensor.这个问题呢？把句子重复几次扩长在输入 这个问题就消失？
